//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/break_glass_credentials_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/break_glass_credentials_type.proto.
 */
export const file_osac_public_v1_break_glass_credentials_type: GenFile = /*@__PURE__*/
  fileDesc("CjFvc2FjL3B1YmxpYy92MS9icmVha19nbGFzc19jcmVkZW50aWFsc190eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSI7ChVCcmVha0dsYXNzQ3JlZGVudGlhbHMSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAliBnByb3RvMw");

/**
 * BreakGlassCredentials contains break-glass account credentials for IdP users.
 * This is only returned during account creation and must be stored securely by the caller.
 *
 * @generated from message osac.public.v1.BreakGlassCredentials
 */
export type BreakGlassCredentials = Message<"osac.public.v1.BreakGlassCredentials"> & {
  /**
   * Username for the account.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * Password for the account.
   * SECURITY: This field contains sensitive data and should be handled carefully:
   * - Only transmitted over TLS
   * - Store in a secure secrets manager (Vault, Kubernetes Secrets, AWS Secrets Manager)
   * - Never log this value
   * - Clear from memory after use
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message osac.public.v1.BreakGlassCredentials.
 * Use `create(BreakGlassCredentialsSchema)` to create a new message.
 */
export const BreakGlassCredentialsSchema: GenMessage<BreakGlassCredentials> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_break_glass_credentials_type, 0);

