//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/capabilities_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { AuthnCapabilities } from "./authn_capabilities_type_pb";
import { file_osac_public_v1_authn_capabilities_type } from "./authn_capabilities_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/capabilities_service.proto.
 */
export const file_osac_public_v1_capabilities_service: GenFile = /*@__PURE__*/
  fileDesc("Cilvc2FjL3B1YmxpYy92MS9jYXBhYmlsaXRpZXNfc2VydmljZS5wcm90bxIOb3NhYy5wdWJsaWMudjEiGAoWQ2FwYWJpbGl0aWVzR2V0UmVxdWVzdCJLChdDYXBhYmlsaXRpZXNHZXRSZXNwb25zZRIwCgVhdXRobhgBIAEoCzIhLm9zYWMucHVibGljLnYxLkF1dGhuQ2FwYWJpbGl0aWVzMpEBCgxDYXBhYmlsaXRpZXMSgAEKA0dldBImLm9zYWMucHVibGljLnYxLkNhcGFiaWxpdGllc0dldFJlcXVlc3QaJy5vc2FjLnB1YmxpYy52MS5DYXBhYmlsaXRpZXNHZXRSZXNwb25zZSIogtPkkwIiEiAvYXBpL2Z1bGZpbGxtZW50L3YxL2NhcGFiaWxpdGllc2IGcHJvdG8z", [file_google_api_annotations, file_osac_public_v1_authn_capabilities_type]);

/**
 * Request message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.public.v1.CapabilitiesGetRequest
 */
export type CapabilitiesGetRequest = Message<"osac.public.v1.CapabilitiesGetRequest"> & {
};

/**
 * Describes the message osac.public.v1.CapabilitiesGetRequest.
 * Use `create(CapabilitiesGetRequestSchema)` to create a new message.
 */
export const CapabilitiesGetRequestSchema: GenMessage<CapabilitiesGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_capabilities_service, 0);

/**
 * Response message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.public.v1.CapabilitiesGetResponse
 */
export type CapabilitiesGetResponse = Message<"osac.public.v1.CapabilitiesGetResponse"> & {
  /**
   * Authentication capabilities of the server.
   *
   * @generated from field: osac.public.v1.AuthnCapabilities authn = 1;
   */
  authn?: AuthnCapabilities | undefined;
};

/**
 * Describes the message osac.public.v1.CapabilitiesGetResponse.
 * Use `create(CapabilitiesGetResponseSchema)` to create a new message.
 */
export const CapabilitiesGetResponseSchema: GenMessage<CapabilitiesGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_capabilities_service, 1);

/**
 * Provides information about the capabilities of the server, such as the list of trusted token issuers for
 * authentication. This endpoint does not require authentication.
 *
 * @generated from service osac.public.v1.Capabilities
 */
export const Capabilities: GenService<{
  /**
   * Returns the capabilities of the server, including the authentication configuration that clients need in order to
   * obtain access tokens.
   *
   * @generated from rpc osac.public.v1.Capabilities.Get
   */
  get: {
    methodKind: "unary";
    input: typeof CapabilitiesGetRequestSchema;
    output: typeof CapabilitiesGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_capabilities_service, 0);

