//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/cluster_catalog_item_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldDefinition } from "./field_definition_type_pb";
import { file_osac_public_v1_field_definition_type } from "./field_definition_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/cluster_catalog_item_type.proto.
 */
export const file_osac_public_v1_cluster_catalog_item_type: GenFile = /*@__PURE__*/
  fileDesc("Ci5vc2FjL3B1YmxpYy92MS9jbHVzdGVyX2NhdGFsb2dfaXRlbV90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSLRAQoSQ2x1c3RlckNhdGFsb2dJdGVtEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESDQoFdGl0bGUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSEAoIdGVtcGxhdGUYBSABKAkSEQoJcHVibGlzaGVkGAYgASgIEjoKEWZpZWxkX2RlZmluaXRpb25zGAggAygLMh8ub3NhYy5wdWJsaWMudjEuRmllbGREZWZpbml0aW9uYgZwcm90bzM", [file_osac_public_v1_field_definition_type, file_osac_public_v1_metadata_type]);

/**
 * A cluster catalog item defines a curated infrastructure offering that references an underlying cluster template.
 * Admins control which fields users can set, enforce defaults, and validate input via JSON Schema.
 *
 * @generated from message osac.public.v1.ClusterCatalogItem
 */
export type ClusterCatalogItem = Message<"osac.public.v1.ClusterCatalogItem"> & {
  /**
   * Unique identifier of the catalog item.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the catalog item, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the catalog item, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Identifier of the underlying cluster template that this catalog item references.
   *
   * @generated from field: string template = 5;
   */
  template: string;

  /**
   * Whether this catalog item is published.
   *
   * @generated from field: bool published = 6;
   */
  published: boolean;

  /**
   * Definitions of the fields that users can or cannot set when creating a resource from this catalog item.
   *
   * @generated from field: repeated osac.public.v1.FieldDefinition field_definitions = 8;
   */
  fieldDefinitions: FieldDefinition[];
};

/**
 * Describes the message osac.public.v1.ClusterCatalogItem.
 * Use `create(ClusterCatalogItemSchema)` to create a new message.
 */
export const ClusterCatalogItemSchema: GenMessage<ClusterCatalogItem> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_cluster_catalog_item_type, 0);

