//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/compute_instance_template_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any } from "../../../google/protobuf/any_pb";
import { file_google_protobuf_any } from "../../../google/protobuf/any_pb";
import type { ComputeInstanceDisk, ComputeInstanceImage } from "./compute_instance_type_pb";
import { file_osac_public_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/compute_instance_template_type.proto.
 */
export const file_osac_public_v1_compute_instance_template_type: GenFile = /*@__PURE__*/
  fileDesc("CjNvc2FjL3B1YmxpYy92MS9jb21wdXRlX2luc3RhbmNlX3RlbXBsYXRlX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIpECChdDb21wdXRlSW5zdGFuY2VUZW1wbGF0ZRIKCgJpZBgBIAEoCRIqCghtZXRhZGF0YRgCIAEoCzIYLm9zYWMucHVibGljLnYxLk1ldGFkYXRhEg0KBXRpdGxlGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEk4KCnBhcmFtZXRlcnMYBSADKAsyOi5vc2FjLnB1YmxpYy52MS5Db21wdXRlSW5zdGFuY2VUZW1wbGF0ZVBhcmFtZXRlckRlZmluaXRpb24SSgoNc3BlY19kZWZhdWx0cxgGIAEoCzIzLm9zYWMucHVibGljLnYxLkNvbXB1dGVJbnN0YW5jZVRlbXBsYXRlU3BlY0RlZmF1bHRzIqUBCipDb21wdXRlSW5zdGFuY2VUZW1wbGF0ZVBhcmFtZXRlckRlZmluaXRpb24SDAoEbmFtZRgBIAEoCRINCgV0aXRsZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIQCghyZXF1aXJlZBgEIAEoCBIMCgR0eXBlGAUgASgJEiUKB2RlZmF1bHQYBiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55IqYCCiNDb21wdXRlSW5zdGFuY2VUZW1wbGF0ZVNwZWNEZWZhdWx0cxISCgVjb3JlcxgBIAEoBUgAiAEBEhcKCm1lbW9yeV9naWIYAiABKAVIAYgBARI4CgVpbWFnZRgDIAEoCzIkLm9zYWMucHVibGljLnYxLkNvbXB1dGVJbnN0YW5jZUltYWdlSAKIAQESOwoJYm9vdF9kaXNrGAQgASgLMiMub3NhYy5wdWJsaWMudjEuQ29tcHV0ZUluc3RhbmNlRGlza0gDiAEBEhkKDHJ1bl9zdHJhdGVneRgFIAEoCUgEiAEBQggKBl9jb3Jlc0INCgtfbWVtb3J5X2dpYkIICgZfaW1hZ2VCDAoKX2Jvb3RfZGlza0IPCg1fcnVuX3N0cmF0ZWd5YgZwcm90bzM", [file_google_protobuf_any, file_osac_public_v1_compute_instance_type, file_osac_public_v1_metadata_type]);

/**
 * A compute instance template defines a type of compute instance that can be created by the user. Note that the user doesn't create these
 * templates: the system provides a collection of them, and the user chooses one.
 *
 * @generated from message osac.public.v1.ComputeInstanceTemplate
 */
export type ComputeInstanceTemplate = Message<"osac.public.v1.ComputeInstanceTemplate"> & {
  /**
   * Unique identifier of the template.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the template, only a few words, suitable for displaying in one single line on a
   * UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the template, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Definitions of the parameters that can be used to customize the template.
   *
   * Note that these are only the *definitions* of the parameters, not the actual values. The actual values are in the
   * `spec.template_parameters` field of the compute instance.
   *
   * @generated from field: repeated osac.public.v1.ComputeInstanceTemplateParameterDefinition parameters = 5;
   */
  parameters: ComputeInstanceTemplateParameterDefinition[];

  /**
   * Default values for compute instance spec fields. When a user creates a
   * compute instance without setting these fields, these values are applied.
   *
   * User-provided spec field values always override these defaults.
   *
   * @generated from field: osac.public.v1.ComputeInstanceTemplateSpecDefaults spec_defaults = 6;
   */
  specDefaults?: ComputeInstanceTemplateSpecDefaults | undefined;
};

/**
 * Describes the message osac.public.v1.ComputeInstanceTemplate.
 * Use `create(ComputeInstanceTemplateSchema)` to create a new message.
 */
export const ComputeInstanceTemplateSchema: GenMessage<ComputeInstanceTemplate> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_compute_instance_template_type, 0);

/**
 * Contains type and documentation of a template parameter.
 *
 * @generated from message osac.public.v1.ComputeInstanceTemplateParameterDefinition
 */
export type ComputeInstanceTemplateParameterDefinition = Message<"osac.public.v1.ComputeInstanceTemplateParameterDefinition"> & {
  /**
   * Name of the parameter.
   *
   * This is the name that should be used in the `template_parameters` field of the compute instance to assign a value to the
   * parameter.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Human friendly short description of the parameter, only a few words, suitable for displaying in one single line on
   * a UI or CLI.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Human friendly description of the parameter, using Markdown format.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Indicates if this parameter is required or optional.
   *
   * Values for required parameters must be included when creating the compute instance, otherwise it will be rejected.
   *
   * Note that there may be other dependencies between parameters which may cause a compute instance to be rejected. For example,
   * the allowed values of a parameter may depend on the value of another parameter. That kind of information will be in
   * the `description` field.
   *
   * @generated from field: bool required = 4;
   */
  required: boolean;

  /**
   * Type of the parameter.
   *
   * The possible values are the same as those used by the `type_url` field of the `Any` type:
   *
   * | Type                           | Value                                             |
   * |--------------------------------|---------------------------------------------------|
   * | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
   * | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
   * | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
   * | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
   * | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
   * | String                         | `type.googleapis.com/google.protobuf.StringValue` |
   * | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
   * | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
   * | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
   * | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
   *
   * When using the HTTP+JSON version of the API the value provided in the `template_parameters` field of the compute instance
   * must be represented as documented in the (ProtoJSON format document)[https://protobuf.dev/programming-guides/json].
   *
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * Default value for optional parameters.
   *
   * @generated from field: google.protobuf.Any default = 6;
   */
  default?: Any | undefined;
};

/**
 * Describes the message osac.public.v1.ComputeInstanceTemplateParameterDefinition.
 * Use `create(ComputeInstanceTemplateParameterDefinitionSchema)` to create a new message.
 */
export const ComputeInstanceTemplateParameterDefinitionSchema: GenMessage<ComputeInstanceTemplateParameterDefinition> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_compute_instance_template_type, 1);

/**
 * Default values for compute instance spec fields.
 *
 * @generated from message osac.public.v1.ComputeInstanceTemplateSpecDefaults
 */
export type ComputeInstanceTemplateSpecDefaults = Message<"osac.public.v1.ComputeInstanceTemplateSpecDefaults"> & {
  /**
   * Default number of CPU cores.
   *
   * @generated from field: optional int32 cores = 1;
   */
  cores?: number | undefined;

  /**
   * Default memory size in GiB.
   *
   * @generated from field: optional int32 memory_gib = 2;
   */
  memoryGib?: number | undefined;

  /**
   * Default image configuration.
   *
   * @generated from field: optional osac.public.v1.ComputeInstanceImage image = 3;
   */
  image?: ComputeInstanceImage | undefined;

  /**
   * Default boot disk configuration.
   *
   * @generated from field: optional osac.public.v1.ComputeInstanceDisk boot_disk = 4;
   */
  bootDisk?: ComputeInstanceDisk | undefined;

  /**
   * Default run strategy.
   *
   * @generated from field: optional string run_strategy = 5;
   */
  runStrategy?: string | undefined;
};

/**
 * Describes the message osac.public.v1.ComputeInstanceTemplateSpecDefaults.
 * Use `create(ComputeInstanceTemplateSpecDefaultsSchema)` to create a new message.
 */
export const ComputeInstanceTemplateSpecDefaultsSchema: GenMessage<ComputeInstanceTemplateSpecDefaults> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_compute_instance_template_type, 2);

