//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/condition_status_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file osac/public/v1/condition_status_type.proto.
 */
export const file_osac_public_v1_condition_status_type: GenFile = /*@__PURE__*/
  fileDesc("Cipvc2FjL3B1YmxpYy92MS9jb25kaXRpb25fc3RhdHVzX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxKmoKD0NvbmRpdGlvblN0YXR1cxIgChxDT05ESVRJT05fU1RBVFVTX1VOU1BFQ0lGSUVEEAASGQoVQ09ORElUSU9OX1NUQVRVU19UUlVFEAESGgoWQ09ORElUSU9OX1NUQVRVU19GQUxTRRACYgZwcm90bzM");

/**
 * @generated from enum osac.public.v1.ConditionStatus
 */
export enum ConditionStatus {
  /**
   * Indicates that the system can't decide if the object is in the condition or not.
   *
   * @generated from enum value: CONDITION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Indicates that the object is in the condition.
   *
   * @generated from enum value: CONDITION_STATUS_TRUE = 1;
   */
  TRUE = 1,

  /**
   * Indicates that the object is not in the condition.
   *
   * @generated from enum value: CONDITION_STATUS_FALSE = 2;
   */
  FALSE = 2,
}

/**
 * Describes the enum osac.public.v1.ConditionStatus.
 */
export const ConditionStatusSchema: GenEnum<ConditionStatus> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_condition_status_type, 0);

