//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/event_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ClusterTemplate } from "./cluster_template_type_pb";
import { file_osac_public_v1_cluster_template_type } from "./cluster_template_type_pb";
import type { Cluster } from "./cluster_type_pb";
import { file_osac_public_v1_cluster_type } from "./cluster_type_pb";
import type { ComputeInstanceTemplate } from "./compute_instance_template_type_pb";
import { file_osac_public_v1_compute_instance_template_type } from "./compute_instance_template_type_pb";
import type { ComputeInstance } from "./compute_instance_type_pb";
import { file_osac_public_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { HostType } from "./host_type_type_pb";
import { file_osac_public_v1_host_type_type } from "./host_type_type_pb";
import type { InstanceType } from "./instance_type_type_pb";
import { file_osac_public_v1_instance_type_type } from "./instance_type_type_pb";
import type { RoleBinding } from "./role_binding_type_pb";
import { file_osac_public_v1_role_binding_type } from "./role_binding_type_pb";
import type { Project } from "./project_type_pb";
import { file_osac_public_v1_project_type } from "./project_type_pb";
import type { Role } from "./role_type_pb";
import { file_osac_public_v1_role_type } from "./role_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/event_type.proto.
 */
export const file_osac_public_v1_event_type: GenFile = /*@__PURE__*/
  fileDesc("Ch9vc2FjL3B1YmxpYy92MS9ldmVudF90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSKoBAoFRXZlbnQSCgoCaWQYASABKAkSJwoEdHlwZRgCIAEoDjIZLm9zYWMucHVibGljLnYxLkV2ZW50VHlwZRIqCgdjbHVzdGVyGAMgASgLMhcub3NhYy5wdWJsaWMudjEuQ2x1c3RlckgAEjsKEGNsdXN0ZXJfdGVtcGxhdGUYBCABKAsyHy5vc2FjLnB1YmxpYy52MS5DbHVzdGVyVGVtcGxhdGVIABItCglob3N0X3R5cGUYBSABKAsyGC5vc2FjLnB1YmxpYy52MS5Ib3N0VHlwZUgAEkwKGWNvbXB1dGVfaW5zdGFuY2VfdGVtcGxhdGUYByABKAsyJy5vc2FjLnB1YmxpYy52MS5Db21wdXRlSW5zdGFuY2VUZW1wbGF0ZUgAEjsKEGNvbXB1dGVfaW5zdGFuY2UYCCABKAsyHy5vc2FjLnB1YmxpYy52MS5Db21wdXRlSW5zdGFuY2VIABIkCgRyb2xlGAkgASgLMhQub3NhYy5wdWJsaWMudjEuUm9sZUgAEjMKDHJvbGVfYmluZGluZxgKIAEoCzIbLm9zYWMucHVibGljLnYxLlJvbGVCaW5kaW5nSAASKgoHcHJvamVjdBgLIAEoCzIXLm9zYWMucHVibGljLnYxLlByb2plY3RIABI1Cg1pbnN0YW5jZV90eXBlGAwgASgLMhwub3NhYy5wdWJsaWMudjEuSW5zdGFuY2VUeXBlSABCCQoHcGF5bG9hZCqEAQoJRXZlbnRUeXBlEhoKFkVWRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIdChlFVkVOVF9UWVBFX09CSkVDVF9DUkVBVEVEEAESHQoZRVZFTlRfVFlQRV9PQkpFQ1RfVVBEQVRFRBACEh0KGUVWRU5UX1RZUEVfT0JKRUNUX0RFTEVURUQQA2IGcHJvdG8z", [file_osac_public_v1_cluster_template_type, file_osac_public_v1_cluster_type, file_osac_public_v1_compute_instance_template_type, file_osac_public_v1_compute_instance_type, file_osac_public_v1_host_type_type, file_osac_public_v1_instance_type_type, file_osac_public_v1_role_binding_type, file_osac_public_v1_project_type, file_osac_public_v1_role_type]);

/**
 * Represents events delivered by the server.
 *
 * @generated from message osac.public.v1.Event
 */
export type Event = Message<"osac.public.v1.Event"> & {
  /**
   * Unique identifier of the event.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Type of event.
   *
   * @generated from field: osac.public.v1.EventType type = 2;
   */
  type: EventType;

  /**
   * Payload of the event.
   *
   * @generated from oneof osac.public.v1.Event.payload
   */
  payload: {
    /**
     * @generated from field: osac.public.v1.Cluster cluster = 3;
     */
    value: Cluster;
    case: "cluster";
  } | {
    /**
     * @generated from field: osac.public.v1.ClusterTemplate cluster_template = 4;
     */
    value: ClusterTemplate;
    case: "clusterTemplate";
  } | {
    /**
     * @generated from field: osac.public.v1.HostType host_type = 5;
     */
    value: HostType;
    case: "hostType";
  } | {
    /**
     * @generated from field: osac.public.v1.ComputeInstanceTemplate compute_instance_template = 7;
     */
    value: ComputeInstanceTemplate;
    case: "computeInstanceTemplate";
  } | {
    /**
     * @generated from field: osac.public.v1.ComputeInstance compute_instance = 8;
     */
    value: ComputeInstance;
    case: "computeInstance";
  } | {
    /**
     * @generated from field: osac.public.v1.Role role = 9;
     */
    value: Role;
    case: "role";
  } | {
    /**
     * @generated from field: osac.public.v1.RoleBinding role_binding = 10;
     */
    value: RoleBinding;
    case: "roleBinding";
  } | {
    /**
     * @generated from field: osac.public.v1.Project project = 11;
     */
    value: Project;
    case: "project";
  } | {
    /**
     * @generated from field: osac.public.v1.InstanceType instance_type = 12;
     */
    value: InstanceType;
    case: "instanceType";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message osac.public.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_event_type, 0);

/**
 * @generated from enum osac.public.v1.EventType
 */
export enum EventType {
  /**
   * Unspecified means that the even type is unknown.
   *
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Means that a new object has been created.
   *
   * The payload will contain the representation of the object.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_CREATED = 1;
   */
  OBJECT_CREATED = 1,

  /**
   * Means that an existing object has been modified.
   *
   * The payload will contain the updated representation of the object.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_UPDATED = 2;
   */
  OBJECT_UPDATED = 2,

  /**
   * Means that an object has been deleted.
   *
   * The payload will contain the representation of the object right before it was deleted.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_DELETED = 3;
   */
  OBJECT_DELETED = 3,
}

/**
 * Describes the enum osac.public.v1.EventType.
 */
export const EventTypeSchema: GenEnum<EventType> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_event_type, 0);

