//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/events_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Event } from "./event_type_pb";
import { file_osac_public_v1_event_type } from "./event_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/events_service.proto.
 */
export const file_osac_public_v1_events_service: GenFile = /*@__PURE__*/
  fileDesc("CiNvc2FjL3B1YmxpYy92MS9ldmVudHNfc2VydmljZS5wcm90bxIOb3NhYy5wdWJsaWMudjEiNAoSRXZlbnRzV2F0Y2hSZXF1ZXN0EhMKBmZpbHRlchgBIAEoCUgAiAEBQgkKB19maWx0ZXIiOwoTRXZlbnRzV2F0Y2hSZXNwb25zZRIkCgVldmVudBgBIAEoCzIVLm9zYWMucHVibGljLnYxLkV2ZW50MnsKBkV2ZW50cxJxCgVXYXRjaBIiLm9zYWMucHVibGljLnYxLkV2ZW50c1dhdGNoUmVxdWVzdBojLm9zYWMucHVibGljLnYxLkV2ZW50c1dhdGNoUmVzcG9uc2UiHYLT5JMCFxIVL2FwaS9ldmVudHMvdjEvZXZlbnRzMAFiBnByb3RvMw", [file_google_api_annotations, file_osac_public_v1_event_type]);

/**
 * @generated from message osac.public.v1.EventsWatchRequest
 */
export type EventsWatchRequest = Message<"osac.public.v1.EventsWatchRequest"> & {
  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) boolean expression. The `event` variable will contain the
   * fields of the event. If the result of the expression is `true` then the event will be sent by the server. For
   * example, to receive only the events that indicate that a cluster order has been modified and is now in the
   * fulfilled state:
   *
   * ```
   * event.type == EVENT_TYPE_OBJECT_CREATED && event.cluster_order.status.state == CLUSTER_ORDER_STATE_FULFILLED
   * ```
   *
   * If this isn't provided, or if the value is empty, then all the events that the user has permission to see will be
   * sent by the server.
   *
   * @generated from field: optional string filter = 1;
   */
  filter?: string | undefined;
};

/**
 * Describes the message osac.public.v1.EventsWatchRequest.
 * Use `create(EventsWatchRequestSchema)` to create a new message.
 */
export const EventsWatchRequestSchema: GenMessage<EventsWatchRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_events_service, 0);

/**
 * @generated from message osac.public.v1.EventsWatchResponse
 */
export type EventsWatchResponse = Message<"osac.public.v1.EventsWatchResponse"> & {
  /**
   * @generated from field: osac.public.v1.Event event = 1;
   */
  event?: Event | undefined;
};

/**
 * Describes the message osac.public.v1.EventsWatchResponse.
 * Use `create(EventsWatchResponseSchema)` to create a new message.
 */
export const EventsWatchResponseSchema: GenMessage<EventsWatchResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_events_service, 1);

/**
 * @generated from service osac.public.v1.Events
 */
export const Events: GenService<{
  /**
   * Start watching events.
   *
   * Note that the server doesn't make any guarantee about the delivery or order of these events. In particular events
   * that happen while the client is disconnected will not be delivered. Clients should consider using other mechanisms
   * to ensure that they process objects correctly. For example, they can combine this watch mechanism with periodic
   * redconciliation of all the objects.
   *
   * @generated from rpc osac.public.v1.Events.Watch
   */
  watch: {
    methodKind: "server_streaming";
    input: typeof EventsWatchRequestSchema;
    output: typeof EventsWatchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_events_service, 0);

