//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/field_definition_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Value } from "../../../google/protobuf/struct_pb";
import { file_google_protobuf_struct } from "../../../google/protobuf/struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/field_definition_type.proto.
 */
export const file_osac_public_v1_field_definition_type: GenFile = /*@__PURE__*/
  fileDesc("Cipvc2FjL3B1YmxpYy92MS9maWVsZF9kZWZpbml0aW9uX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIosBCg9GaWVsZERlZmluaXRpb24SDAoEcGF0aBgBIAEoCRIUCgxkaXNwbGF5X25hbWUYAiABKAkSEAoIZWRpdGFibGUYAyABKAgSJwoHZGVmYXVsdBgEIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZRIZChF2YWxpZGF0aW9uX3NjaGVtYRgFIAEoCWIGcHJvdG8z", [file_google_protobuf_struct]);

/**
 * Defines a single field on the resource spec that a catalog item controls.
 *
 * @generated from message osac.public.v1.FieldDefinition
 */
export type FieldDefinition = Message<"osac.public.v1.FieldDefinition"> & {
  /**
   * Dot-notation path referencing a field in the resource spec.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * Human friendly label for this field, suitable for displaying in a UI.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Whether the user is allowed to set this field.
   *
   * @generated from field: bool editable = 3;
   */
  editable: boolean;

  /**
   * Default value for this field.
   *
   * @generated from field: google.protobuf.Value default = 4;
   */
  default?: Value | undefined;

  /**
   * Optional JSON Schema (draft 2020-12) for validating user-provided values of editable fields.
   *
   * @generated from field: string validation_schema = 5;
   */
  validationSchema: string;
};

/**
 * Describes the message osac.public.v1.FieldDefinition.
 * Use `create(FieldDefinitionSchema)` to create a new message.
 */
export const FieldDefinitionSchema: GenMessage<FieldDefinition> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_field_definition_type, 0);

