//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/host_type_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/host_type_type.proto.
 */
export const file_osac_public_v1_host_type_type: GenFile = /*@__PURE__*/
  fileDesc("CiNvc2FjL3B1YmxpYy92MS9ob3N0X3R5cGVfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEiZgoISG9zdFR5cGUSCgoCaWQYASABKAkSKgoIbWV0YWRhdGEYAiABKAsyGC5vc2FjLnB1YmxpYy52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCWIGcHJvdG8z", [file_osac_public_v1_metadata_type]);

/**
 * Describes a set of hosts that share characteristics.
 *
 * For example there could be a host type `acme_1tb` to describe the set of hosts manifactured by ACME and with 1 TiB
 * of RAM, and another `ibm_mi300x` to describe the set of hosts manufactured IBM and with a MI300X GPU.
 *
 * This is similar to the _instance type_ concept used by many cloud providers.
 *
 * The detailed chracteristics of the host (CPU, memory, GPU, etc) will be in the `description` field.
 *
 * @generated from message osac.public.v1.HostType
 */
export type HostType = Message<"osac.public.v1.HostType"> & {
  /**
   * Unique identifier of the type.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the host type.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the host type, only a few words, suitable for displaying in one single
   * line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the host type, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * Describes the message osac.public.v1.HostType.
 * Use `create(HostTypeSchema)` to create a new message.
 */
export const HostTypeSchema: GenMessage<HostType> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_host_type_type, 0);

