//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/metadata_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import { file_google_protobuf_timestamp } from "../../../google/protobuf/timestamp_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/metadata_type.proto.
 */
export const file_osac_public_v1_metadata_type: GenFile = /*@__PURE__*/
  fileDesc("CiJvc2FjL3B1YmxpYy92MS9tZXRhZGF0YV90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSKTAwoITWV0YWRhdGESNgoSY3JlYXRpb25fdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI2ChJkZWxldGlvbl90aW1lc3RhbXAYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEg8KB2NyZWF0b3IYAyABKAkSDAoEbmFtZRgEIAEoCRIOCgZ0ZW5hbnQYBSABKAkSNAoGbGFiZWxzGAcgAygLMiQub3NhYy5wdWJsaWMudjEuTWV0YWRhdGEuTGFiZWxzRW50cnkSPgoLYW5ub3RhdGlvbnMYCCADKAsyKS5vc2FjLnB1YmxpYy52MS5NZXRhZGF0YS5Bbm5vdGF0aW9uc0VudHJ5Eg8KB3ZlcnNpb24YCSABKAUaLQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARoyChBBbm5vdGF0aW9uc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Metadata common to all kinds of objects.
 *
 * @generated from message osac.public.v1.Metadata
 */
export type Metadata = Message<"osac.public.v1.Metadata"> & {
  /**
   * Time of creation of the object.
   *
   * @generated from field: google.protobuf.Timestamp creation_timestamp = 1;
   */
  creationTimestamp?: Timestamp | undefined;

  /**
   * Time of deletion of the object.
   *
   * @generated from field: google.protobuf.Timestamp deletion_timestamp = 2;
   */
  deletionTimestamp?: Timestamp | undefined;

  /**
   * Name of the creator of the object.
   *
   * @generated from field: string creator = 3;
   */
  creator: string;

  /**
   * Human friendly name of the object.
   *
   * Has the same restrictions than DNS labels, as described in RFC 1035:
   *
   * - Must be between 1 and 63 characters long.
   * - Must only contain letters (a-z), digits (0-9) and hyphens (-).
   * - It isn't case sensitive.
   *
   * It is optional and not unique, so multiple objecs, even created by the same user or tenant, can have the same name.
   *
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * Identifier of the tenant that the object is assigned to.
   *
   * @generated from field: string tenant = 5;
   */
  tenant: string;

  /**
   * Labels contains key-value pairs for organizing and selecting objects.
   *
   * Keys consist of an optional prefix and a name separated by '/':
   *
   * - Prefix is a DNS subdomain (RFC 1035) and must be between 1 and 253 characters long.
   * - Name must be between 1 and 63 characters long, start and end with an alphanumeric character, and contain only
   *   letters (a-z), digits (0-9), '-' '_' or '.'.
   *
   * Values are optional; when present they must be between 0 and 63 characters long and follow the same character
   * rules as names.
   *
   * Labels are indexed and searchable.
   *
   * @generated from field: map<string, string> labels = 7;
   */
  labels: { [key: string]: string };

  /**
   * Annotations contains arbitrary metadata for objects.
   *
   * Keys follow the same rules as label keys, including the optional DNS subdomain prefix and the 1-63 character name
   * restrictions. Values can be any string.
   *
   * @generated from field: map<string, string> annotations = 8;
   */
  annotations: { [key: string]: string };

  /**
   * Version is a numeric field that is automatically incremented with every change to the object.
   *
   * @generated from field: int32 version = 9;
   */
  version: number;
};

/**
 * Describes the message osac.public.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_metadata_type, 0);

