//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/network_class_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/network_class_type.proto.
 */
export const file_osac_public_v1_network_class_type: GenFile = /*@__PURE__*/
  fileDesc("Cidvc2FjL3B1YmxpYy92MS9uZXR3b3JrX2NsYXNzX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIosCCgxOZXR3b3JrQ2xhc3MSCgoCaWQYASABKAkSKgoIbWV0YWRhdGEYAiABKAsyGC5vc2FjLnB1YmxpYy52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRI+CgxjYXBhYmlsaXRpZXMYByABKAsyKC5vc2FjLnB1YmxpYy52MS5OZXR3b3JrQ2xhc3NDYXBhYmlsaXRpZXMSMgoGc3RhdHVzGAggASgLMiIub3NhYy5wdWJsaWMudjEuTmV0d29ya0NsYXNzU3RhdHVzEhwKCmlzX2RlZmF1bHQYCSABKAhCA+BBA0gAiAEBQg0KC19pc19kZWZhdWx0ImUKGE5ldHdvcmtDbGFzc0NhcGFiaWxpdGllcxIVCg1zdXBwb3J0c19pcHY0GAEgASgIEhUKDXN1cHBvcnRzX2lwdjYYAiABKAgSGwoTc3VwcG9ydHNfZHVhbF9zdGFjaxgDIAEoCCJoChJOZXR3b3JrQ2xhc3NTdGF0dXMSMAoFc3RhdGUYASABKA4yIS5vc2FjLnB1YmxpYy52MS5OZXR3b3JrQ2xhc3NTdGF0ZRIUCgdtZXNzYWdlGAIgASgJSACIAQFCCgoIX21lc3NhZ2UqmAEKEU5ldHdvcmtDbGFzc1N0YXRlEiMKH05FVFdPUktfQ0xBU1NfU1RBVEVfVU5TUEVDSUZJRUQQABIfChtORVRXT1JLX0NMQVNTX1NUQVRFX1BFTkRJTkcQARIdChlORVRXT1JLX0NMQVNTX1NUQVRFX1JFQURZEAISHgoaTkVUV09SS19DTEFTU19TVEFURV9GQUlMRUQQA2IGcHJvdG8z", [file_google_api_field_behavior, file_osac_public_v1_metadata_type]);

/**
 * Describes a network implementation strategy available for creating virtual networks.
 *
 * NetworkClass represents a specific network backend implementation that VirtualNetworks can use. For example,
 * there could be a network class `udn-net` to describe networks implemented using User-Defined Networks in
 * Kubernetes, and another `phys-net` for networks backed by physical network infrastructure.
 *
 * This is similar to the _storage class_ concept used by Kubernetes for persistent volumes, or the _instance type_
 * concept used by cloud providers for compute resources.
 *
 * Users query available NetworkClasses to discover which network types they can choose when
 * creating VirtualNetworks.
 *
 * @generated from message osac.public.v1.NetworkClass
 */
export type NetworkClass = Message<"osac.public.v1.NetworkClass"> & {
  /**
   * Unique identifier of the network class.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the network class.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the network class, only a few words, suitable for displaying in one single
   * line on a UI or CLI. For example: "UDN Network" or "Physical Network".
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the network class, using Markdown format. This should explain the
   * characteristics of networks created using this class, including performance characteristics, isolation
   * guarantees, and any limitations or requirements.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Capabilities that this network class supports. These describe what features are available when using this
   * network class.
   *
   * @generated from field: osac.public.v1.NetworkClassCapabilities capabilities = 7;
   */
  capabilities?: NetworkClassCapabilities | undefined;

  /**
   * Current operational status of the network class.
   *
   * @generated from field: osac.public.v1.NetworkClassStatus status = 8;
   */
  status?: NetworkClassStatus | undefined;

  /**
   * Whether this NetworkClass is the default. Only one NetworkClass can be the default at a time.
   * When a VirtualNetwork is created without specifying network_class, the default NetworkClass is used.
   *
   * @generated from field: optional bool is_default = 9;
   */
  isDefault?: boolean | undefined;
};

/**
 * Describes the message osac.public.v1.NetworkClass.
 * Use `create(NetworkClassSchema)` to create a new message.
 */
export const NetworkClassSchema: GenMessage<NetworkClass> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_network_class_type, 0);

/**
 * Describes the capabilities supported by a NetworkClass.
 *
 * These fields indicate what network features are available when using this class for VirtualNetwork creation.
 *
 * @generated from message osac.public.v1.NetworkClassCapabilities
 */
export type NetworkClassCapabilities = Message<"osac.public.v1.NetworkClassCapabilities"> & {
  /**
   * Whether this network class supports IPv4 addressing.
   *
   * @generated from field: bool supports_ipv4 = 1;
   */
  supportsIpv4: boolean;

  /**
   * Whether this network class supports IPv6 addressing.
   *
   * @generated from field: bool supports_ipv6 = 2;
   */
  supportsIpv6: boolean;

  /**
   * Whether this network class supports dual-stack (IPv4 + IPv6) configuration.
   *
   * @generated from field: bool supports_dual_stack = 3;
   */
  supportsDualStack: boolean;
};

/**
 * Describes the message osac.public.v1.NetworkClassCapabilities.
 * Use `create(NetworkClassCapabilitiesSchema)` to create a new message.
 */
export const NetworkClassCapabilitiesSchema: GenMessage<NetworkClassCapabilities> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_network_class_type, 1);

/**
 * Represents the current operational state of a NetworkClass.
 *
 * @generated from message osac.public.v1.NetworkClassStatus
 */
export type NetworkClassStatus = Message<"osac.public.v1.NetworkClassStatus"> & {
  /**
   * Current lifecycle state of the network class.
   *
   * @generated from field: osac.public.v1.NetworkClassState state = 1;
   */
  state: NetworkClassState;

  /**
   * Human-readable message providing additional details about the current state. For example, if the state is
   * FAILED, this message might explain what went wrong.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.NetworkClassStatus.
 * Use `create(NetworkClassStatusSchema)` to create a new message.
 */
export const NetworkClassStatusSchema: GenMessage<NetworkClassStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_network_class_type, 2);

/**
 * Lifecycle states for NetworkClass resources.
 *
 * @generated from enum osac.public.v1.NetworkClassState
 */
export enum NetworkClassState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: NETWORK_CLASS_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The network class is being initialized and is not yet ready for use.
   *
   * @generated from enum value: NETWORK_CLASS_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The network class is fully operational and available for creating VirtualNetworks.
   *
   * @generated from enum value: NETWORK_CLASS_STATE_READY = 2;
   */
  READY = 2,

  /**
   * The network class has encountered an error and cannot be used for creating VirtualNetworks.
   *
   * @generated from enum value: NETWORK_CLASS_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.NetworkClassState.
 */
export const NetworkClassStateSchema: GenEnum<NetworkClassState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_network_class_type, 0);

