//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/openapi_options.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb";

/**
 * Describes the file osac/public/v1/openapi_options.proto.
 */
export const file_osac_public_v1_openapi_options: GenFile = /*@__PURE__*/
  fileDesc("CiRvc2FjL3B1YmxpYy92MS9vcGVuYXBpX29wdGlvbnMucHJvdG8SDm9zYWMucHVibGljLnYxQsUBkkHBARKXAQoIT1NBQyBBUEkiLwoMT1NBQyBQcm9qZWN0Eh9odHRwczovL2dpdGh1Yi5jb20vb3NhYy1wcm9qZWN0KlMKCkFwYWNoZS0yLjASRWh0dHBzOi8vZ2l0aHViLmNvbS9vc2FjLXByb2plY3QvZnVsZmlsbG1lbnQtc2VydmljZS9ibG9iL21haW4vTElDRU5TRTIFMC4wLjEqAQIyEGFwcGxpY2F0aW9uL2pzb246EGFwcGxpY2F0aW9uL2pzb25iBnByb3RvMw", [file_protoc_gen_openapiv2_options_annotations]);

