//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/organization_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/organization_type.proto.
 */
export const file_osac_public_v1_organization_type: GenFile = /*@__PURE__*/
  fileDesc("CiZvc2FjL3B1YmxpYy92MS9vcmdhbml6YXRpb25fdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEidgoMT3JnYW5pemF0aW9uEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESLgoEc3BlYxgDIAEoCzIgLm9zYWMucHVibGljLnYxLk9yZ2FuaXphdGlvblNwZWMiEgoQT3JnYW5pemF0aW9uU3BlY2IGcHJvdG8z", [file_osac_public_v1_metadata_type]);

/**
 * An organization groups tenants and resources for a customer or business unit.
 *
 * @generated from message osac.public.v1.Organization
 */
export type Organization = Message<"osac.public.v1.Organization"> & {
  /**
   * Unique identifier of the organization.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * @generated from field: osac.public.v1.OrganizationSpec spec = 3;
   */
  spec?: OrganizationSpec | undefined;
};

/**
 * Describes the message osac.public.v1.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export const OrganizationSchema: GenMessage<Organization> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_organization_type, 0);

/**
 * Reserved for future organization configuration fields.
 *
 * @generated from message osac.public.v1.OrganizationSpec
 */
export type OrganizationSpec = Message<"osac.public.v1.OrganizationSpec"> & {
};

/**
 * Describes the message osac.public.v1.OrganizationSpec.
 * Use `create(OrganizationSpecSchema)` to create a new message.
 */
export const OrganizationSpecSchema: GenMessage<OrganizationSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_organization_type, 1);

