//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/public_ip_pools_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { PublicIPPool } from "./public_ip_pool_type_pb";
import { file_osac_public_v1_public_ip_pool_type } from "./public_ip_pool_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/public_ip_pools_service.proto.
 */
export const file_osac_public_v1_public_ip_pools_service: GenFile = /*@__PURE__*/
  fileDesc("Cixvc2FjL3B1YmxpYy92MS9wdWJsaWNfaXBfcG9vbHNfc2VydmljZS5wcm90bxIOb3NhYy5wdWJsaWMudjEieAoYUHVibGljSVBQb29sc0xpc3RSZXF1ZXN0EhMKBm9mZnNldBgBIAEoBUgAiAEBEhIKBWxpbWl0GAIgASgFSAGIAQESEwoGZmlsdGVyGAMgASgJSAKIAQFCCQoHX29mZnNldEIICgZfbGltaXRCCQoHX2ZpbHRlciJlChlQdWJsaWNJUFBvb2xzTGlzdFJlc3BvbnNlEgwKBHNpemUYASABKAUSDQoFdG90YWwYAiABKAUSKwoFaXRlbXMYAyADKAsyHC5vc2FjLnB1YmxpYy52MS5QdWJsaWNJUFBvb2wiJQoXUHVibGljSVBQb29sc0dldFJlcXVlc3QSCgoCaWQYASABKAkiSAoYUHVibGljSVBQb29sc0dldFJlc3BvbnNlEiwKBm9iamVjdBgBIAEoCzIcLm9zYWMucHVibGljLnYxLlB1YmxpY0lQUG9vbDKvAgoNUHVibGljSVBQb29scxKIAQoETGlzdBIoLm9zYWMucHVibGljLnYxLlB1YmxpY0lQUG9vbHNMaXN0UmVxdWVzdBopLm9zYWMucHVibGljLnYxLlB1YmxpY0lQUG9vbHNMaXN0UmVzcG9uc2UiK4LT5JMCJRIjL2FwaS9mdWxmaWxsbWVudC92MS9wdWJsaWNfaXBfcG9vbHMSkgEKA0dldBInLm9zYWMucHVibGljLnYxLlB1YmxpY0lQUG9vbHNHZXRSZXF1ZXN0Gigub3NhYy5wdWJsaWMudjEuUHVibGljSVBQb29sc0dldFJlc3BvbnNlIjiC0+STAjJiBm9iamVjdBIoL2FwaS9mdWxmaWxsbWVudC92MS9wdWJsaWNfaXBfcG9vbHMve2lkfWIGcHJvdG8z", [file_google_api_annotations, file_osac_public_v1_public_ip_pool_type]);

/**
 * @generated from message osac.public.v1.PublicIPPoolsListRequest
 */
export type PublicIPPoolsListRequest = Message<"osac.public.v1.PublicIPPoolsListRequest"> & {
  /**
   * Index of the first result. If not specified the default value will be zero.
   *
   * @generated from field: optional int32 offset = 1;
   */
  offset?: number | undefined;

  /**
   * Maximum number of results to be returned by the server. When not specified all the results will be returned.
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number | undefined;

  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
   * built-in `this` variable refers to the object being tested. For example, to retrieve all IPv4 pools:
   *
   *     this.spec.ip_family == IP_FAMILY_IPV4
   *
   * If this isn't provided, or if the value is empty, then all pools visible to the user are returned.
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIPPoolsListRequest.
 * Use `create(PublicIPPoolsListRequestSchema)` to create a new message.
 */
export const PublicIPPoolsListRequestSchema: GenMessage<PublicIPPoolsListRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pools_service, 0);

/**
 * @generated from message osac.public.v1.PublicIPPoolsListResponse
 */
export type PublicIPPoolsListResponse = Message<"osac.public.v1.PublicIPPoolsListResponse"> & {
  /**
   * Actual number of items returned.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Total number of items matching the search criteria.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * List of results.
   *
   * @generated from field: repeated osac.public.v1.PublicIPPool items = 3;
   */
  items: PublicIPPool[];
};

/**
 * Describes the message osac.public.v1.PublicIPPoolsListResponse.
 * Use `create(PublicIPPoolsListResponseSchema)` to create a new message.
 */
export const PublicIPPoolsListResponseSchema: GenMessage<PublicIPPoolsListResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pools_service, 1);

/**
 * @generated from message osac.public.v1.PublicIPPoolsGetRequest
 */
export type PublicIPPoolsGetRequest = Message<"osac.public.v1.PublicIPPoolsGetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.PublicIPPoolsGetRequest.
 * Use `create(PublicIPPoolsGetRequestSchema)` to create a new message.
 */
export const PublicIPPoolsGetRequestSchema: GenMessage<PublicIPPoolsGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pools_service, 2);

/**
 * @generated from message osac.public.v1.PublicIPPoolsGetResponse
 */
export type PublicIPPoolsGetResponse = Message<"osac.public.v1.PublicIPPoolsGetResponse"> & {
  /**
   * @generated from field: osac.public.v1.PublicIPPool object = 1;
   */
  object?: PublicIPPool | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIPPoolsGetResponse.
 * Use `create(PublicIPPoolsGetResponseSchema)` to create a new message.
 */
export const PublicIPPoolsGetResponseSchema: GenMessage<PublicIPPoolsGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pools_service, 3);

/**
 * @generated from service osac.public.v1.PublicIPPools
 */
export const PublicIPPools: GenService<{
  /**
   * Retrieves the list of public IP pools visible to the caller.
   *
   * @generated from rpc osac.public.v1.PublicIPPools.List
   */
  list: {
    methodKind: "unary";
    input: typeof PublicIPPoolsListRequestSchema;
    output: typeof PublicIPPoolsListResponseSchema;
  },
  /**
   * Retrieves the details of one specific public IP pool.
   *
   * @generated from rpc osac.public.v1.PublicIPPools.Get
   */
  get: {
    methodKind: "unary";
    input: typeof PublicIPPoolsGetRequestSchema;
    output: typeof PublicIPPoolsGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_public_ip_pools_service, 0);

