//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/public_ip_pool_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/public_ip_pool_type.proto.
 */
export const file_osac_public_v1_public_ip_pool_type: GenFile = /*@__PURE__*/
  fileDesc("Cihvc2FjL3B1YmxpYy92MS9wdWJsaWNfaXBfcG9vbF90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSKqAQoMUHVibGljSVBQb29sEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESLgoEc3BlYxgDIAEoCzIgLm9zYWMucHVibGljLnYxLlB1YmxpY0lQUG9vbFNwZWMSMgoGc3RhdHVzGAQgASgLMiIub3NhYy5wdWJsaWMudjEuUHVibGljSVBQb29sU3RhdHVzIlgKEFB1YmxpY0lQUG9vbFNwZWMSEgoFY2lkcnMYAiADKAlCA+BBBRIwCglpcF9mYW1pbHkYAyABKA4yGC5vc2FjLnB1YmxpYy52MS5JUEZhbWlseUID4EEFIiwKElB1YmxpY0lQUG9vbFN0YXR1cxIWCglhdmFpbGFibGUYBiABKANCA+BBAypNCghJUEZhbWlseRIZChVJUF9GQU1JTFlfVU5TUEVDSUZJRUQQABISCg5JUF9GQU1JTFlfSVBWNBABEhIKDklQX0ZBTUlMWV9JUFY2EAJiBnByb3RvMw", [file_google_api_field_behavior, file_osac_public_v1_metadata_type]);

/**
 * Represents a pool of public IP addresses available for allocation.
 *
 * PublicIPPools are administrator-managed resources. The public API only surfaces pools that are
 * ready and have available capacity.
 * Tenants use this resource to discover available pools and select one when allocating a PublicIP.
 *
 * @generated from message osac.public.v1.PublicIPPool
 */
export type PublicIPPool = Message<"osac.public.v1.PublicIPPool"> & {
  /**
   * Unique identifier of the public IP pool.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the public IP pool, including name, labels, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Configuration of the public IP pool.
   *
   * @generated from field: osac.public.v1.PublicIPPoolSpec spec = 3;
   */
  spec?: PublicIPPoolSpec | undefined;

  /**
   * Current capacity information for this pool (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.PublicIPPoolStatus status = 4;
   */
  status?: PublicIPPoolStatus | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIPPool.
 * Use `create(PublicIPPoolSchema)` to create a new message.
 */
export const PublicIPPoolSchema: GenMessage<PublicIPPool> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pool_type, 0);

/**
 * Defines the configuration of a PublicIPPool.
 *
 * Field 1 is reserved for future use.
 *
 * @generated from message osac.public.v1.PublicIPPoolSpec
 */
export type PublicIPPoolSpec = Message<"osac.public.v1.PublicIPPoolSpec"> & {
  /**
   * CIDR ranges for this pool. Immutable after creation.
   *
   * @generated from field: repeated string cidrs = 2;
   */
  cidrs: string[];

  /**
   * IP address family for this pool. Immutable after creation.
   *
   * @generated from field: osac.public.v1.IPFamily ip_family = 3;
   */
  ipFamily: IPFamily;
};

/**
 * Describes the message osac.public.v1.PublicIPPoolSpec.
 * Use `create(PublicIPPoolSpecSchema)` to create a new message.
 */
export const PublicIPPoolSpecSchema: GenMessage<PublicIPPoolSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pool_type, 1);

/**
 * Capacity information for a PublicIPPool exposed to tenants.
 *
 * @generated from message osac.public.v1.PublicIPPoolStatus
 */
export type PublicIPPoolStatus = Message<"osac.public.v1.PublicIPPoolStatus"> & {
  /**
   * Number of IP addresses available for new allocations from this pool.
   *
   * @generated from field: int64 available = 6;
   */
  available: bigint;
};

/**
 * Describes the message osac.public.v1.PublicIPPoolStatus.
 * Use `create(PublicIPPoolStatusSchema)` to create a new message.
 */
export const PublicIPPoolStatusSchema: GenMessage<PublicIPPoolStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_pool_type, 2);

/**
 * IP address family for a PublicIPPool.
 *
 * @generated from enum osac.public.v1.IPFamily
 */
export enum IPFamily {
  /**
   * IP family is unknown or has not been specified.
   *
   * @generated from enum value: IP_FAMILY_UNSPECIFIED = 0;
   */
  IP_FAMILY_UNSPECIFIED = 0,

  /**
   * IPv4 address family.
   *
   * @generated from enum value: IP_FAMILY_IPV4 = 1;
   */
  IP_FAMILY_IPV4 = 1,

  /**
   * IPv6 address family.
   *
   * @generated from enum value: IP_FAMILY_IPV6 = 2;
   */
  IP_FAMILY_IPV6 = 2,
}

/**
 * Describes the enum osac.public.v1.IPFamily.
 */
export const IPFamilySchema: GenEnum<IPFamily> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_public_ip_pool_type, 0);

