//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/public_ip_attachment_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/public_ip_attachment_type.proto.
 */
export const file_osac_public_v1_public_ip_attachment_type: GenFile = /*@__PURE__*/
  fileDesc("Ci5vc2FjL3B1YmxpYy92MS9wdWJsaWNfaXBfYXR0YWNobWVudF90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSK8AQoSUHVibGljSVBBdHRhY2htZW50EgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESNAoEc3BlYxgDIAEoCzImLm9zYWMucHVibGljLnYxLlB1YmxpY0lQQXR0YWNobWVudFNwZWMSOAoGc3RhdHVzGAQgASgLMigub3NhYy5wdWJsaWMudjEuUHVibGljSVBBdHRhY2htZW50U3RhdHVzIlkKFlB1YmxpY0lQQXR0YWNobWVudFNwZWMSGQoJcHVibGljX2lwGAEgASgJQgbgQQLgQQUSGgoQY29tcHV0ZV9pbnN0YW5jZRgCIAEoCUgAQggKBnRhcmdldCKeAQoYUHVibGljSVBBdHRhY2htZW50U3RhdHVzEjsKBXN0YXRlGAEgASgOMicub3NhYy5wdWJsaWMudjEuUHVibGljSVBBdHRhY2htZW50U3RhdGVCA+BBAxIeChFwdWJsaWNfaXBfYWRkcmVzcxgCIAEoCUID4EEDEhkKB21lc3NhZ2UYAyABKAlCA+BBA0gAiAEBQgoKCF9tZXNzYWdlKroBChdQdWJsaWNJUEF0dGFjaG1lbnRTdGF0ZRIqCiZQVUJMSUNfSVBfQVRUQUNITUVOVF9TVEFURV9VTlNQRUNJRklFRBAAEiYKIlBVQkxJQ19JUF9BVFRBQ0hNRU5UX1NUQVRFX1BFTkRJTkcQARIkCiBQVUJMSUNfSVBfQVRUQUNITUVOVF9TVEFURV9SRUFEWRACEiUKIVBVQkxJQ19JUF9BVFRBQ0hNRU5UX1NUQVRFX0ZBSUxFRBADYgZwcm90bzM", [file_google_api_field_behavior, file_osac_public_v1_metadata_type]);

/**
 * Represents a binding between a PublicIP and a target resource (e.g., a ComputeInstance).
 *
 * A PublicIPAttachment is a first-class resource that manages the attach/detach lifecycle
 * independently from the PublicIP allocation lifecycle. Creating a PublicIPAttachment triggers
 * the attach workflow; deleting it triggers the detach workflow.
 *
 * The binding is immutable: to change the target, delete the attachment and create a new one.
 * The oneof target field supports future target types (Cluster, BareMetalServer) without
 * breaking changes.
 *
 * Lifecycle: PENDING (attach in progress) -> READY (attached and routing traffic).
 * FAILED is a terminal error state that retries via the standard provisioning lifecycle
 * with exponential backoff.
 *
 * @generated from message osac.public.v1.PublicIPAttachment
 */
export type PublicIPAttachment = Message<"osac.public.v1.PublicIPAttachment"> & {
  /**
   * Unique identifier of the public IP attachment.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the public IP attachment, including name, labels, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the public IP attachment (user-specified).
   *
   * @generated from field: osac.public.v1.PublicIPAttachmentSpec spec = 3;
   */
  spec?: PublicIPAttachmentSpec | undefined;

  /**
   * Current state of the public IP attachment (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.PublicIPAttachmentStatus status = 4;
   */
  status?: PublicIPAttachmentStatus | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIPAttachment.
 * Use `create(PublicIPAttachmentSchema)` to create a new message.
 */
export const PublicIPAttachmentSchema: GenMessage<PublicIPAttachment> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_attachment_type, 0);

/**
 * Defines the desired configuration for a PublicIPAttachment.
 *
 * Both fields are required and immutable after creation. The public_ip must reference an
 * existing PublicIP in ALLOCATED state. The target must reference a valid resource that
 * supports public IP attachment.
 *
 * @generated from message osac.public.v1.PublicIPAttachmentSpec
 */
export type PublicIPAttachmentSpec = Message<"osac.public.v1.PublicIPAttachmentSpec"> & {
  /**
   * PublicIP ID to attach. Required and immutable after creation.
   *
   * Must reference the ID of an existing PublicIP in ALLOCATED state that is not already
   * attached (status.attached == false). Only one PublicIPAttachment may exist per PublicIP.
   *
   * Example: "019728a4-3f5c-7def-8abc-1234567890ab"
   *
   * @generated from field: string public_ip = 1;
   */
  publicIp: string;

  /**
   * Target resource to attach the public IP to. Exactly one target field must be set.
   * Required and immutable after creation.
   *
   * @generated from oneof osac.public.v1.PublicIPAttachmentSpec.target
   */
  target: {
    /**
     * ComputeInstance ID to attach this public IP to.
     *
     * Must reference the ID of an existing ComputeInstance in RUNNING state. Only one
     * PublicIPAttachment may exist per ComputeInstance.
     *
     * Example: "01972f1b-a4e9-7c82-9def-abcdef123456"
     *
     * @generated from field: string compute_instance = 2;
     */
    value: string;
    case: "computeInstance";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message osac.public.v1.PublicIPAttachmentSpec.
 * Use `create(PublicIPAttachmentSpecSchema)` to create a new message.
 */
export const PublicIPAttachmentSpecSchema: GenMessage<PublicIPAttachmentSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_attachment_type, 1);

/**
 * Represents the current operational state of a PublicIPAttachment.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the
 * system updates them based on reconciliation of the spec and feedback from the cluster
 * controller.
 *
 * @generated from message osac.public.v1.PublicIPAttachmentStatus
 */
export type PublicIPAttachmentStatus = Message<"osac.public.v1.PublicIPAttachmentStatus"> & {
  /**
   * Current lifecycle state of the public IP attachment.
   *
   * @generated from field: osac.public.v1.PublicIPAttachmentState state = 1;
   */
  state: PublicIPAttachmentState;

  /**
   * Allocated IP address from the parent PublicIP.
   *
   * Populated for convenience once the attachment reaches READY state. Mirrors the address
   * field from the referenced PublicIP's status.
   *
   * @generated from field: string public_ip_address = 2;
   */
  publicIpAddress: string;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, may contain progress information. For FAILED state, contains the
   * error details. Typically empty for READY state.
   *
   * @generated from field: optional string message = 3;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIPAttachmentStatus.
 * Use `create(PublicIPAttachmentStatusSchema)` to create a new message.
 */
export const PublicIPAttachmentStatusSchema: GenMessage<PublicIPAttachmentStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_attachment_type, 2);

/**
 * Lifecycle states for PublicIPAttachment resources.
 *
 * State transitions: UNSPECIFIED -> PENDING -> READY.
 * FAILED can occur from PENDING and retries automatically via the provisioning lifecycle.
 *
 * @generated from enum osac.public.v1.PublicIPAttachmentState
 */
export enum PublicIPAttachmentState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED = 0;
   */
  PUBLIC_IP_ATTACHMENT_STATE_UNSPECIFIED = 0,

  /**
   * The attachment is being provisioned (attach workflow in progress).
   *
   * The system is binding the PublicIP's allocated address to the target resource.
   *
   * @generated from enum value: PUBLIC_IP_ATTACHMENT_STATE_PENDING = 1;
   */
  PUBLIC_IP_ATTACHMENT_STATE_PENDING = 1,

  /**
   * The attachment is active and the target is reachable via the public IP address.
   *
   * The PublicIP's allocated address is bound to the target resource and actively routing
   * traffic. The parent PublicIP's status.attached is set to true.
   *
   * @generated from enum value: PUBLIC_IP_ATTACHMENT_STATE_READY = 2;
   */
  PUBLIC_IP_ATTACHMENT_STATE_READY = 2,

  /**
   * The attachment failed. Check status.message for error details.
   *
   * The provisioning lifecycle retries automatically with exponential backoff.
   *
   * @generated from enum value: PUBLIC_IP_ATTACHMENT_STATE_FAILED = 3;
   */
  PUBLIC_IP_ATTACHMENT_STATE_FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.PublicIPAttachmentState.
 */
export const PublicIPAttachmentStateSchema: GenEnum<PublicIPAttachmentState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_public_ip_attachment_type, 0);

