//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/public_ip_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/public_ip_type.proto.
 */
export const file_osac_public_v1_public_ip_type: GenFile = /*@__PURE__*/
  fileDesc("CiNvc2FjL3B1YmxpYy92MS9wdWJsaWNfaXBfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEingEKCFB1YmxpY0lQEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESKgoEc3BlYxgDIAEoCzIcLm9zYWMucHVibGljLnYxLlB1YmxpY0lQU3BlYxIuCgZzdGF0dXMYBCABKAsyHi5vc2FjLnB1YmxpYy52MS5QdWJsaWNJUFN0YXR1cyIkCgxQdWJsaWNJUFNwZWMSFAoEcG9vbBgBIAEoCUIG4EEC4EEFIqoBCg5QdWJsaWNJUFN0YXR1cxIxCgVzdGF0ZRgBIAEoDjIdLm9zYWMucHVibGljLnYxLlB1YmxpY0lQU3RhdGVCA+BBAxIZCgdtZXNzYWdlGAIgASgJQgPgQQNIAIgBARIUCgdhZGRyZXNzGAMgASgJQgPgQQMSEQoEcG9vbBgEIAEoCUID4EEDEhUKCGF0dGFjaGVkGAUgASgIQgPgQQNCCgoIX21lc3NhZ2UqpgEKDVB1YmxpY0lQU3RhdGUSHwobUFVCTElDX0lQX1NUQVRFX1VOU1BFQ0lGSUVEEAASGwoXUFVCTElDX0lQX1NUQVRFX1BFTkRJTkcQARIdChlQVUJMSUNfSVBfU1RBVEVfQUxMT0NBVEVEEAISGgoWUFVCTElDX0lQX1NUQVRFX0ZBSUxFRBADEhwKGFBVQkxJQ19JUF9TVEFURV9ERUxFVElORxAEYgZwcm90bzM", [file_google_api_field_behavior, file_osac_public_v1_metadata_type]);

/**
 * Represents a public IP address allocated from a PublicIPPool.
 *
 * A PublicIP is a floating public IP address allocated from a parent PublicIPPool's CIDR ranges.
 * The pool assignment is immutable after creation.
 *
 * Attachment to a target resource (e.g., ComputeInstance) is managed by a separate
 * PublicIPAttachment resource. The status.attached boolean indicates whether a
 * PublicIPAttachment currently exists for this PublicIP.
 *
 * The lifecycle follows: PENDING (awaiting allocation) -> ALLOCATED (IP assigned).
 * FAILED is a terminal error state for provisioning failures.
 *
 * @generated from message osac.public.v1.PublicIP
 */
export type PublicIP = Message<"osac.public.v1.PublicIP"> & {
  /**
   * Unique identifier of the public IP.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the public IP, including name, labels, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the public IP (user-specified).
   *
   * @generated from field: osac.public.v1.PublicIPSpec spec = 3;
   */
  spec?: PublicIPSpec | undefined;

  /**
   * Current state of the public IP (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.PublicIPStatus status = 4;
   */
  status?: PublicIPStatus | undefined;
};

/**
 * Describes the message osac.public.v1.PublicIP.
 * Use `create(PublicIPSchema)` to create a new message.
 */
export const PublicIPSchema: GenMessage<PublicIP> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_type, 0);

/**
 * Defines the desired configuration for a PublicIP.
 *
 * The pool field is required and immutable: once a PublicIP is allocated from a pool, it cannot
 * be moved to a different pool.
 *
 * @generated from message osac.public.v1.PublicIPSpec
 */
export type PublicIPSpec = Message<"osac.public.v1.PublicIPSpec"> & {
  /**
   * Parent PublicIPPool ID. Required and immutable after creation.
   *
   * Must reference the ID of an existing PublicIPPool in READY state. The system allocates an
   * available IP address from this pool's CIDR ranges during provisioning.
   *
   * Example: "pool-abc123"
   *
   * @generated from field: string pool = 1;
   */
  pool: string;
};

/**
 * Describes the message osac.public.v1.PublicIPSpec.
 * Use `create(PublicIPSpecSchema)` to create a new message.
 */
export const PublicIPSpecSchema: GenMessage<PublicIPSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_type, 1);

/**
 * Represents the current operational state of a PublicIP.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the system
 * updates them based on reconciliation of the spec and feedback from the cluster controller.
 *
 * @generated from message osac.public.v1.PublicIPStatus
 */
export type PublicIPStatus = Message<"osac.public.v1.PublicIPStatus"> & {
  /**
   * Current lifecycle state of the public IP.
   *
   * @generated from field: osac.public.v1.PublicIPState state = 1;
   */
  state: PublicIPState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, may contain progress information like "Waiting for IP allocation".
   * Typically empty for ALLOCATED state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;

  /**
   * Allocated IP address from the parent pool's CIDR range.
   *
   * Populated once the IP transitions to ALLOCATED state. Remains stable for the lifetime of
   * the PublicIP. Cleared only when the IP is deallocated.
   *
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * Parent PublicIPPool ID that this IP was allocated from.
   *
   * Mirrors spec.pool for convenience in status queries. Populated when the IP is allocated.
   *
   * @generated from field: string pool = 4;
   */
  pool: string;

  /**
   * Whether this PublicIP is currently attached to a target resource via a PublicIPAttachment.
   *
   * Set to true when a PublicIPAttachment referencing this PublicIP reaches READY state.
   * Set to false when the PublicIPAttachment is deleted. A PublicIP with attached = true
   * cannot be deleted; the PublicIPAttachment must be deleted first.
   *
   * @generated from field: bool attached = 5;
   */
  attached: boolean;
};

/**
 * Describes the message osac.public.v1.PublicIPStatus.
 * Use `create(PublicIPStatusSchema)` to create a new message.
 */
export const PublicIPStatusSchema: GenMessage<PublicIPStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_public_ip_type, 2);

/**
 * Lifecycle states for PublicIP resources.
 *
 * State transitions: UNSPECIFIED -> PENDING -> ALLOCATED.
 * FAILED is a terminal error state for provisioning failures.
 *
 * @generated from enum osac.public.v1.PublicIPState
 */
export enum PublicIPState {
  /**
   * State is unknown or has not been determined yet. Default state before initialization.
   *
   * @generated from enum value: PUBLIC_IP_STATE_UNSPECIFIED = 0;
   */
  PUBLIC_IP_STATE_UNSPECIFIED = 0,

  /**
   * The public IP is being provisioned and an address has not been assigned yet.
   *
   * During this state, the system is creating the MetalLB LoadBalancer Service on the target
   * cluster and waiting for an IP address to be allocated from the parent pool's CIDR range.
   *
   * @generated from enum value: PUBLIC_IP_STATE_PENDING = 1;
   */
  PUBLIC_IP_STATE_PENDING = 1,

  /**
   * The public IP has been assigned an address.
   *
   * The address is allocated and reserved. The IP can be attached to a target resource by
   * creating a PublicIPAttachment. The status.attached boolean indicates whether an
   * attachment currently exists.
   *
   * @generated from enum value: PUBLIC_IP_STATE_ALLOCATED = 2;
   */
  PUBLIC_IP_STATE_ALLOCATED = 2,

  /**
   * Provisioning failed. Check status.message for error details.
   *
   * This is a terminal error state. The PublicIP may require deletion and recreation,
   * or an administrator can retry via the private API Signal RPC.
   *
   * @generated from enum value: PUBLIC_IP_STATE_FAILED = 3;
   */
  PUBLIC_IP_STATE_FAILED = 3,

  /**
   * The public IP is being deprovisioned and will be removed.
   *
   * On deletion of a PublicIP, the system removes the MetalLB LoadBalancer Service and
   * returns the address to the pool. A PublicIP cannot be deleted while attached
   * (status.attached = true). The resource remains visible in this state until fully
   * cleaned up.
   *
   * @generated from enum value: PUBLIC_IP_STATE_DELETING = 4;
   */
  PUBLIC_IP_STATE_DELETING = 4,
}

/**
 * Describes the enum osac.public.v1.PublicIPState.
 */
export const PublicIPStateSchema: GenEnum<PublicIPState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_public_ip_type, 0);

