//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/role_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/role_type.proto.
 */
export const file_osac_public_v1_role_type: GenFile = /*@__PURE__*/
  fileDesc("Ch5vc2FjL3B1YmxpYy92MS9yb2xlX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIpIBCgRSb2xlEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESJgoEc3BlYxgDIAEoCzIYLm9zYWMucHVibGljLnYxLlJvbGVTcGVjEioKBnN0YXR1cxgEIAEoCzIaLm9zYWMucHVibGljLnYxLlJvbGVTdGF0dXMiLgoIUm9sZVNwZWMSDQoFdGl0bGUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkiWAoKUm9sZVN0YXR1cxIoCgVzdGF0ZRgBIAEoDjIZLm9zYWMucHVibGljLnYxLlJvbGVTdGF0ZRIUCgdtZXNzYWdlGAIgASgJSACIAQFCCgoIX21lc3NhZ2UqbAoJUm9sZVN0YXRlEhoKFlJPTEVfU1RBVEVfVU5TUEVDSUZJRUQQABIWChJST0xFX1NUQVRFX1BFTkRJTkcQARIUChBST0xFX1NUQVRFX1JFQURZEAISFQoRUk9MRV9TVEFURV9GQUlMRUQQA2IGcHJvdG8z", [file_osac_public_v1_metadata_type]);

/**
 * Represents a role that can be assigned to groups.
 *
 * Roles are predefined named entities that represent a set of permissions within the system. They are assigned to
 * groups to control what actions the members of those groups can perform. Roles themselves do not carry any data
 * beyond their identity and metadata; the actual permissions are determined by the system based on the role name.
 *
 * Examples of predefined roles include `cloud-provider-admin`, `tenant-admin`, and `tenant-reader`.
 *
 * @generated from message osac.public.v1.Role
 */
export type Role = Message<"osac.public.v1.Role"> & {
  /**
   * Unique identifier of the role.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the role.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired state of the role.
   *
   * @generated from field: osac.public.v1.RoleSpec spec = 3;
   */
  spec?: RoleSpec | undefined;

  /**
   * Current observed state of the role.
   *
   * @generated from field: osac.public.v1.RoleStatus status = 4;
   */
  status?: RoleStatus | undefined;
};

/**
 * Describes the message osac.public.v1.Role.
 * Use `create(RoleSchema)` to create a new message.
 */
export const RoleSchema: GenMessage<Role> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_type, 0);

/**
 * Desired state of a role.
 *
 * @generated from message osac.public.v1.RoleSpec
 */
export type RoleSpec = Message<"osac.public.v1.RoleSpec"> & {
  /**
   * Human-friendly short description of the role, only a few words, suitable for displaying in one single line on
   * a UI or CLI. For example: "Cloud Provider Administrator" or "Tenant Reader".
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * Human-friendly long description of the role, using Markdown format. This should explain what permissions the
   * role grants and in what contexts it is typically used.
   *
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message osac.public.v1.RoleSpec.
 * Use `create(RoleSpecSchema)` to create a new message.
 */
export const RoleSpecSchema: GenMessage<RoleSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_type, 1);

/**
 * Current observed state of a role, reflecting its synchronization with the underlying authorization system.
 *
 * @generated from message osac.public.v1.RoleStatus
 */
export type RoleStatus = Message<"osac.public.v1.RoleStatus"> & {
  /**
   * Current synchronization state of the role.
   *
   * @generated from field: osac.public.v1.RoleState state = 1;
   */
  state: RoleState;

  /**
   * Human-readable message providing additional details about the current state. For example, if the state is
   * FAILED, this field may explain why the synchronization with the authorization system failed.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.RoleStatus.
 * Use `create(RoleStatusSchema)` to create a new message.
 */
export const RoleStatusSchema: GenMessage<RoleStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_type, 2);

/**
 * Synchronization states for Role resources with the underlying authorization system.
 *
 * @generated from enum osac.public.v1.RoleState
 */
export enum RoleState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: ROLE_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The role is being created or applied to the underlying authorization system and cannot be used yet.
   *
   * @generated from enum value: ROLE_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The role is fully synchronized with the underlying authorization system and can be used.
   *
   * @generated from enum value: ROLE_STATE_READY = 2;
   */
  READY = 2,

  /**
   * The role failed to be applied to the underlying authorization system.
   *
   * @generated from enum value: ROLE_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.RoleState.
 */
export const RoleStateSchema: GenEnum<RoleState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_role_type, 0);

