//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/role_binding_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/role_binding_type.proto.
 */
export const file_osac_public_v1_role_binding_type: GenFile = /*@__PURE__*/
  fileDesc("CiZvc2FjL3B1YmxpYy92MS9yb2xlX2JpbmRpbmdfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEipwEKC1JvbGVCaW5kaW5nEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESLQoEc3BlYxgDIAEoCzIfLm9zYWMucHVibGljLnYxLlJvbGVCaW5kaW5nU3BlYxIxCgZzdGF0dXMYBCABKAsyIS5vc2FjLnB1YmxpYy52MS5Sb2xlQmluZGluZ1N0YXR1cyIvCg9Sb2xlQmluZGluZ1NwZWMSDAoEcm9sZRgBIAEoCRIOCgZncm91cHMYAiADKAkiZgoRUm9sZUJpbmRpbmdTdGF0dXMSLwoFc3RhdGUYASABKA4yIC5vc2FjLnB1YmxpYy52MS5Sb2xlQmluZGluZ1N0YXRlEhQKB21lc3NhZ2UYAiABKAlIAIgBAUIKCghfbWVzc2FnZSqTAQoQUm9sZUJpbmRpbmdTdGF0ZRIiCh5ST0xFX0JJTkRJTkdfU1RBVEVfVU5TUEVDSUZJRUQQABIeChpST0xFX0JJTkRJTkdfU1RBVEVfUEVORElORxABEhwKGFJPTEVfQklORElOR19TVEFURV9SRUFEWRACEh0KGVJPTEVfQklORElOR19TVEFURV9GQUlMRUQQA2IGcHJvdG8z", [file_osac_public_v1_metadata_type]);

/**
 * Represents a binding between a role and a set of subjects (groups).
 *
 * A RoleBinding grants the permissions defined by its referenced role to the subjects listed in its spec. This is
 * the mechanism by which roles are assigned to groups, enabling the members of those groups to perform the actions
 * permitted by the role.
 *
 * The subjects of a RoleBinding are groups as defined by the identity provider (IDP) of the tenant. This service
 * does not manage groups directly; it references them by their IDP-assigned identifiers. For example, if a tenant
 * uses Keycloak as its identity provider, the values in the `groups` field correspond to the names of Keycloak
 * groups within the tenant's realm.
 *
 * @generated from message osac.public.v1.RoleBinding
 */
export type RoleBinding = Message<"osac.public.v1.RoleBinding"> & {
  /**
   * Unique identifier of the role binding.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the role binding.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired state of the role binding.
   *
   * @generated from field: osac.public.v1.RoleBindingSpec spec = 3;
   */
  spec?: RoleBindingSpec | undefined;

  /**
   * Current observed state of the role binding.
   *
   * @generated from field: osac.public.v1.RoleBindingStatus status = 4;
   */
  status?: RoleBindingStatus | undefined;
};

/**
 * Describes the message osac.public.v1.RoleBinding.
 * Use `create(RoleBindingSchema)` to create a new message.
 */
export const RoleBindingSchema: GenMessage<RoleBinding> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_binding_type, 0);

/**
 * Desired state of a role binding.
 *
 * @generated from message osac.public.v1.RoleBindingSpec
 */
export type RoleBindingSpec = Message<"osac.public.v1.RoleBindingSpec"> & {
  /**
   * Identifier of the role that this binding refers to. This determines which permissions are granted to the
   * subjects listed below.
   *
   * @generated from field: string role = 1;
   */
  role: string;

  /**
   * Identifiers of the groups that are granted the permissions defined by the role. These are group identifiers
   * as defined by the identity provider (IDP) of the tenant, not internal system identifiers. For example, in a
   * Keycloak-based deployment these would be the Keycloak group names within the tenant's realm.
   *
   * @generated from field: repeated string groups = 2;
   */
  groups: string[];
};

/**
 * Describes the message osac.public.v1.RoleBindingSpec.
 * Use `create(RoleBindingSpecSchema)` to create a new message.
 */
export const RoleBindingSpecSchema: GenMessage<RoleBindingSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_binding_type, 1);

/**
 * Current observed state of a role binding, reflecting its synchronization with the underlying authorization system.
 *
 * @generated from message osac.public.v1.RoleBindingStatus
 */
export type RoleBindingStatus = Message<"osac.public.v1.RoleBindingStatus"> & {
  /**
   * Current synchronization state of the role binding.
   *
   * @generated from field: osac.public.v1.RoleBindingState state = 1;
   */
  state: RoleBindingState;

  /**
   * Human-readable message providing additional details about the current state. For example, if the state is
   * FAILED, this field may explain why the synchronization with the authorization system failed.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.RoleBindingStatus.
 * Use `create(RoleBindingStatusSchema)` to create a new message.
 */
export const RoleBindingStatusSchema: GenMessage<RoleBindingStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_role_binding_type, 2);

/**
 * Synchronization states for RoleBinding objects with the underlying authorization system.
 *
 * @generated from enum osac.public.v1.RoleBindingState
 */
export enum RoleBindingState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: ROLE_BINDING_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The role binding is being applied to the underlying authorization system and is not yet effective.
   *
   * @generated from enum value: ROLE_BINDING_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The role binding is fully synchronized with the underlying authorization system and is effective.
   *
   * @generated from enum value: ROLE_BINDING_STATE_READY = 2;
   */
  READY = 2,

  /**
   * The role binding failed to be applied to the underlying authorization system.
   *
   * @generated from enum value: ROLE_BINDING_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.RoleBindingState.
 */
export const RoleBindingStateSchema: GenEnum<RoleBindingState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_role_binding_type, 0);

