//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/users_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { FieldMask } from "../../../google/protobuf/field_mask_pb";
import { file_google_protobuf_field_mask } from "../../../google/protobuf/field_mask_pb";
import type { User } from "./user_type_pb";
import { file_osac_public_v1_user_type } from "./user_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/users_service.proto.
 */
export const file_osac_public_v1_users_service: GenFile = /*@__PURE__*/
  fileDesc("CiJvc2FjL3B1YmxpYy92MS91c2Vyc19zZXJ2aWNlLnByb3RvEg5vc2FjLnB1YmxpYy52MSKOAQoQVXNlcnNMaXN0UmVxdWVzdBITCgZvZmZzZXQYASABKAVIAIgBARISCgVsaW1pdBgCIAEoBUgBiAEBEhMKBmZpbHRlchgDIAEoCUgCiAEBEhIKBW9yZGVyGAQgASgJSAOIAQFCCQoHX29mZnNldEIICgZfbGltaXRCCQoHX2ZpbHRlckIICgZfb3JkZXIiVQoRVXNlcnNMaXN0UmVzcG9uc2USDAoEc2l6ZRgBIAEoBRINCgV0b3RhbBgCIAEoBRIjCgVpdGVtcxgDIAMoCzIULm9zYWMucHVibGljLnYxLlVzZXIiHQoPVXNlcnNHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIjgKEFVzZXJzR2V0UmVzcG9uc2USJAoGb2JqZWN0GAEgASgLMhQub3NhYy5wdWJsaWMudjEuVXNlciI6ChJVc2Vyc0NyZWF0ZVJlcXVlc3QSJAoGb2JqZWN0GAEgASgLMhQub3NhYy5wdWJsaWMudjEuVXNlciI7ChNVc2Vyc0NyZWF0ZVJlc3BvbnNlEiQKBm9iamVjdBgBIAEoCzIULm9zYWMucHVibGljLnYxLlVzZXIieQoSVXNlcnNVcGRhdGVSZXF1ZXN0EiQKBm9iamVjdBgBIAEoCzIULm9zYWMucHVibGljLnYxLlVzZXISLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrEgwKBGxvY2sYAyABKAgiOwoTVXNlcnNVcGRhdGVSZXNwb25zZRIkCgZvYmplY3QYASABKAsyFC5vc2FjLnB1YmxpYy52MS5Vc2VyIiAKElVzZXJzRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCSIVChNVc2Vyc0RlbGV0ZVJlc3BvbnNlMoYFCgVVc2VycxJuCgRMaXN0EiAub3NhYy5wdWJsaWMudjEuVXNlcnNMaXN0UmVxdWVzdBohLm9zYWMucHVibGljLnYxLlVzZXJzTGlzdFJlc3BvbnNlIiGC0+STAhsSGS9hcGkvZnVsZmlsbG1lbnQvdjEvdXNlcnMSeAoDR2V0Eh8ub3NhYy5wdWJsaWMudjEuVXNlcnNHZXRSZXF1ZXN0GiAub3NhYy5wdWJsaWMudjEuVXNlcnNHZXRSZXNwb25zZSIugtPkkwIoYgZvYmplY3QSHi9hcGkvZnVsZmlsbG1lbnQvdjEvdXNlcnMve2lkfRKEAQoGQ3JlYXRlEiIub3NhYy5wdWJsaWMudjEuVXNlcnNDcmVhdGVSZXF1ZXN0GiMub3NhYy5wdWJsaWMudjEuVXNlcnNDcmVhdGVSZXNwb25zZSIxgtPkkwIrOgZvYmplY3RiBm9iamVjdCIZL2FwaS9mdWxmaWxsbWVudC92MS91c2VycxKQAQoGVXBkYXRlEiIub3NhYy5wdWJsaWMudjEuVXNlcnNVcGRhdGVSZXF1ZXN0GiMub3NhYy5wdWJsaWMudjEuVXNlcnNVcGRhdGVSZXNwb25zZSI9gtPkkwI3OgZvYmplY3RiBm9iamVjdDIlL2FwaS9mdWxmaWxsbWVudC92MS91c2Vycy97b2JqZWN0LmlkfRJ5CgZEZWxldGUSIi5vc2FjLnB1YmxpYy52MS5Vc2Vyc0RlbGV0ZVJlcXVlc3QaIy5vc2FjLnB1YmxpYy52MS5Vc2Vyc0RlbGV0ZVJlc3BvbnNlIiaC0+STAiAqHi9hcGkvZnVsZmlsbG1lbnQvdjEvdXNlcnMve2lkfWIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_field_mask, file_osac_public_v1_user_type]);

/**
 * @generated from message osac.public.v1.UsersListRequest
 */
export type UsersListRequest = Message<"osac.public.v1.UsersListRequest"> & {
  /**
   * Index of the first result. If not specified the default value will be zero.
   *
   * @generated from field: optional int32 offset = 1;
   */
  offset?: number | undefined;

  /**
   * Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
   * that there may not be enough results to return, and that the server may decide, for performance reasons, to return
   * less results than requested.
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number | undefined;

  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return.
   * If this isn't provided, or if the value is empty, then all the users that the caller has permission to see will be
   * returned.
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string | undefined;

  /**
   * Order criteria.
   *
   * The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
   * names of the attributes of the user instead of the names of the columns of a table. For example, in order to
   * sort the users descending by username the value should be:
   *
   *     username desc
   *
   * If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
   *
   * @generated from field: optional string order = 4;
   */
  order?: string | undefined;
};

/**
 * Describes the message osac.public.v1.UsersListRequest.
 * Use `create(UsersListRequestSchema)` to create a new message.
 */
export const UsersListRequestSchema: GenMessage<UsersListRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 0);

/**
 * @generated from message osac.public.v1.UsersListResponse
 */
export type UsersListResponse = Message<"osac.public.v1.UsersListResponse"> & {
  /**
   * Actual number of items returned.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Total number of items matching the search criteria.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * List of users.
   *
   * @generated from field: repeated osac.public.v1.User items = 3;
   */
  items: User[];
};

/**
 * Describes the message osac.public.v1.UsersListResponse.
 * Use `create(UsersListResponseSchema)` to create a new message.
 */
export const UsersListResponseSchema: GenMessage<UsersListResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 1);

/**
 * @generated from message osac.public.v1.UsersGetRequest
 */
export type UsersGetRequest = Message<"osac.public.v1.UsersGetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.UsersGetRequest.
 * Use `create(UsersGetRequestSchema)` to create a new message.
 */
export const UsersGetRequestSchema: GenMessage<UsersGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 2);

/**
 * @generated from message osac.public.v1.UsersGetResponse
 */
export type UsersGetResponse = Message<"osac.public.v1.UsersGetResponse"> & {
  /**
   * @generated from field: osac.public.v1.User object = 1;
   */
  object?: User | undefined;
};

/**
 * Describes the message osac.public.v1.UsersGetResponse.
 * Use `create(UsersGetResponseSchema)` to create a new message.
 */
export const UsersGetResponseSchema: GenMessage<UsersGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 3);

/**
 * @generated from message osac.public.v1.UsersCreateRequest
 */
export type UsersCreateRequest = Message<"osac.public.v1.UsersCreateRequest"> & {
  /**
   * @generated from field: osac.public.v1.User object = 1;
   */
  object?: User | undefined;
};

/**
 * Describes the message osac.public.v1.UsersCreateRequest.
 * Use `create(UsersCreateRequestSchema)` to create a new message.
 */
export const UsersCreateRequestSchema: GenMessage<UsersCreateRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 4);

/**
 * @generated from message osac.public.v1.UsersCreateResponse
 */
export type UsersCreateResponse = Message<"osac.public.v1.UsersCreateResponse"> & {
  /**
   * @generated from field: osac.public.v1.User object = 1;
   */
  object?: User | undefined;
};

/**
 * Describes the message osac.public.v1.UsersCreateResponse.
 * Use `create(UsersCreateResponseSchema)` to create a new message.
 */
export const UsersCreateResponseSchema: GenMessage<UsersCreateResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 5);

/**
 * @generated from message osac.public.v1.UsersUpdateRequest
 */
export type UsersUpdateRequest = Message<"osac.public.v1.UsersUpdateRequest"> & {
  /**
   * @generated from field: osac.public.v1.User object = 1;
   */
  object?: User | undefined;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask | undefined;

  /**
   * Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
   * matches the value of the metadata.version field of the submitted object. If they differ the update will be
   * rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
   *
   * @generated from field: bool lock = 3;
   */
  lock: boolean;
};

/**
 * Describes the message osac.public.v1.UsersUpdateRequest.
 * Use `create(UsersUpdateRequestSchema)` to create a new message.
 */
export const UsersUpdateRequestSchema: GenMessage<UsersUpdateRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 6);

/**
 * @generated from message osac.public.v1.UsersUpdateResponse
 */
export type UsersUpdateResponse = Message<"osac.public.v1.UsersUpdateResponse"> & {
  /**
   * @generated from field: osac.public.v1.User object = 1;
   */
  object?: User | undefined;
};

/**
 * Describes the message osac.public.v1.UsersUpdateResponse.
 * Use `create(UsersUpdateResponseSchema)` to create a new message.
 */
export const UsersUpdateResponseSchema: GenMessage<UsersUpdateResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 7);

/**
 * @generated from message osac.public.v1.UsersDeleteRequest
 */
export type UsersDeleteRequest = Message<"osac.public.v1.UsersDeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.UsersDeleteRequest.
 * Use `create(UsersDeleteRequestSchema)` to create a new message.
 */
export const UsersDeleteRequestSchema: GenMessage<UsersDeleteRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 8);

/**
 * @generated from message osac.public.v1.UsersDeleteResponse
 */
export type UsersDeleteResponse = Message<"osac.public.v1.UsersDeleteResponse"> & {
};

/**
 * Describes the message osac.public.v1.UsersDeleteResponse.
 * Use `create(UsersDeleteResponseSchema)` to create a new message.
 */
export const UsersDeleteResponseSchema: GenMessage<UsersDeleteResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_users_service, 9);

/**
 * @generated from service osac.public.v1.Users
 */
export const Users: GenService<{
  /**
   * Retrieves the list of users.
   *
   * @generated from rpc osac.public.v1.Users.List
   */
  list: {
    methodKind: "unary";
    input: typeof UsersListRequestSchema;
    output: typeof UsersListResponseSchema;
  },
  /**
   * Retrieves the details of one specific user.
   *
   * @generated from rpc osac.public.v1.Users.Get
   */
  get: {
    methodKind: "unary";
    input: typeof UsersGetRequestSchema;
    output: typeof UsersGetResponseSchema;
  },
  /**
   * Creates a new user.
   *
   * @generated from rpc osac.public.v1.Users.Create
   */
  create: {
    methodKind: "unary";
    input: typeof UsersCreateRequestSchema;
    output: typeof UsersCreateResponseSchema;
  },
  /**
   * Updates an existing user.
   *
   * @generated from rpc osac.public.v1.Users.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UsersUpdateRequestSchema;
    output: typeof UsersUpdateResponseSchema;
  },
  /**
   * Deletes a user.
   *
   * @generated from rpc osac.public.v1.Users.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof UsersDeleteRequestSchema;
    output: typeof UsersDeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_users_service, 0);

