//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/user_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import { file_google_protobuf_timestamp } from "../../../google/protobuf/timestamp_pb";
import type { ConditionStatus } from "./condition_status_type_pb";
import { file_osac_public_v1_condition_status_type } from "./condition_status_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/user_type.proto.
 */
export const file_osac_public_v1_user_type: GenFile = /*@__PURE__*/
  fileDesc("Ch5vc2FjL3B1YmxpYy92MS91c2VyX3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIpIBCgRVc2VyEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESJgoEc3BlYxgDIAEoCzIYLm9zYWMucHVibGljLnYxLlVzZXJTcGVjEioKBnN0YXR1cxgEIAEoCzIaLm9zYWMucHVibGljLnYxLlVzZXJTdGF0dXMi3AEKCFVzZXJTcGVjEhAKCHVzZXJuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhYKDmVtYWlsX3ZlcmlmaWVkGAMgASgIEg8KB2VuYWJsZWQYBCABKAgSEgoKZmlyc3RfbmFtZRgFIAEoCRIRCglsYXN0X25hbWUYBiABKAkSFAoMb3JnYW5pemF0aW9uGAcgASgJEjkKC2NyZWRlbnRpYWxzGAggASgLMh8ub3NhYy5wdWJsaWMudjEuVXNlckNyZWRlbnRpYWxzSACIAQFCDgoMX2NyZWRlbnRpYWxzIlEKD1VzZXJDcmVkZW50aWFscxIVCghwYXNzd29yZBgBIAEoCUgAiAEBEhoKEnRlbXBvcmFyeV9wYXNzd29yZBgCIAEoCEILCglfcGFzc3dvcmQiTgoKVXNlclN0YXR1cxINCgVwaGFzZRgBIAEoCRIxCgpjb25kaXRpb25zGAIgAygLMh0ub3NhYy5wdWJsaWMudjEuVXNlckNvbmRpdGlvbiLKAQoNVXNlckNvbmRpdGlvbhIMCgR0eXBlGAEgASgJEi8KBnN0YXR1cxgCIAEoDjIfLm9zYWMucHVibGljLnYxLkNvbmRpdGlvblN0YXR1cxI4ChRsYXN0X3RyYW5zaXRpb25fdGltZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEwoGcmVhc29uGAQgASgJSACIAQESFAoHbWVzc2FnZRgFIAEoCUgBiAEBQgkKB19yZWFzb25CCgoIX21lc3NhZ2ViBnByb3RvMw", [file_google_protobuf_timestamp, file_osac_public_v1_condition_status_type, file_osac_public_v1_metadata_type]);

/**
 * A user in an organization's identity provider.
 *
 * @generated from message osac.public.v1.User
 */
export type User = Message<"osac.public.v1.User"> & {
  /**
   * Unique identifier of the user.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Specification of the user.
   *
   * @generated from field: osac.public.v1.UserSpec spec = 3;
   */
  spec?: UserSpec | undefined;

  /**
   * Status of the user.
   *
   * @generated from field: osac.public.v1.UserStatus status = 4;
   */
  status?: UserStatus | undefined;
};

/**
 * Describes the message osac.public.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_user_type, 0);

/**
 * UserSpec contains the desired state of the user.
 *
 * @generated from message osac.public.v1.UserSpec
 */
export type UserSpec = Message<"osac.public.v1.UserSpec"> & {
  /**
   * Username for authentication.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * Email address.
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * Whether the email has been verified.
   *
   * @generated from field: bool email_verified = 3;
   */
  emailVerified: boolean;

  /**
   * Whether the user account is enabled.
   *
   * @generated from field: bool enabled = 4;
   */
  enabled: boolean;

  /**
   * First name of the user.
   *
   * @generated from field: string first_name = 5;
   */
  firstName: string;

  /**
   * Last name of the user.
   *
   * @generated from field: string last_name = 6;
   */
  lastName: string;

  /**
   * Organization that this user belongs to.
   *
   * @generated from field: string organization = 7;
   */
  organization: string;

  /**
   * Credentials for the user. This is write-only and will not be returned in responses.
   *
   * @generated from field: optional osac.public.v1.UserCredentials credentials = 8;
   */
  credentials?: UserCredentials | undefined;
};

/**
 * Describes the message osac.public.v1.UserSpec.
 * Use `create(UserSpecSchema)` to create a new message.
 */
export const UserSpecSchema: GenMessage<UserSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_user_type, 1);

/**
 * UserCredentials contains the authentication credentials for a user.
 *
 * @generated from message osac.public.v1.UserCredentials
 */
export type UserCredentials = Message<"osac.public.v1.UserCredentials"> & {
  /**
   * Password for the user.
   *
   * SECURITY: This field contains sensitive data:
   * - Only transmitted over TLS
   * - Never returned in responses
   * - Clear from memory after use
   *
   * @generated from field: optional string password = 1;
   */
  password?: string | undefined;

  /**
   * Whether the password is temporary and must be changed on first login. Only applicable when password is provided.
   *
   * @generated from field: bool temporary_password = 2;
   */
  temporaryPassword: boolean;
};

/**
 * Describes the message osac.public.v1.UserCredentials.
 * Use `create(UserCredentialsSchema)` to create a new message.
 */
export const UserCredentialsSchema: GenMessage<UserCredentials> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_user_type, 2);

/**
 * UserStatus contains the observed state of the user.
 *
 * @generated from message osac.public.v1.UserStatus
 */
export type UserStatus = Message<"osac.public.v1.UserStatus"> & {
  /**
   * The user's current state in the identity provider.
   *
   * @generated from field: string phase = 1;
   */
  phase: string;

  /**
   * Additional conditions about the user's state.
   *
   * @generated from field: repeated osac.public.v1.UserCondition conditions = 2;
   */
  conditions: UserCondition[];
};

/**
 * Describes the message osac.public.v1.UserStatus.
 * Use `create(UserStatusSchema)` to create a new message.
 */
export const UserStatusSchema: GenMessage<UserStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_user_type, 3);

/**
 * UserCondition represents a condition of a user.
 *
 * @generated from message osac.public.v1.UserCondition
 */
export type UserCondition = Message<"osac.public.v1.UserCondition"> & {
  /**
   * Type of the condition.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Status of the condition.
   *
   * @generated from field: osac.public.v1.ConditionStatus status = 2;
   */
  status: ConditionStatus;

  /**
   * Last time the condition was updated.
   *
   * @generated from field: google.protobuf.Timestamp last_transition_time = 3;
   */
  lastTransitionTime?: Timestamp | undefined;

  /**
   * Reason for the condition's last transition.
   *
   * @generated from field: optional string reason = 4;
   */
  reason?: string | undefined;

  /**
   * Human-readable message about the transition.
   *
   * @generated from field: optional string message = 5;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.UserCondition.
 * Use `create(UserConditionSchema)` to create a new message.
 */
export const UserConditionSchema: GenMessage<UserCondition> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_user_type, 4);

